PROJECT_NAME           = "{{PROJECT_TITLE}} C++ API"
PROJECT_BRIEF          = "Authored native host and Lua bridge API"
OUTPUT_DIRECTORY       = build/docs/cpp
INPUT                  = app/src/main/cpp modules
FILE_PATTERNS          = *.h *.hpp *.c *.cc *.cpp
RECURSIVE              = YES
EXCLUDE_PATTERNS       = */third_party/*
EXTRACT_ALL            = NO
EXTRACT_PRIVATE        = NO
EXTRACT_STATIC         = NO
HIDE_UNDOC_MEMBERS     = YES
HIDE_UNDOC_CLASSES     = YES
JAVADOC_AUTOBRIEF      = YES
MARKDOWN_SUPPORT       = YES
AUTOLINK_SUPPORT       = YES
GENERATE_HTML          = YES
HTML_OUTPUT            = html
GENERATE_XML           = YES
XML_OUTPUT             = xml
GENERATE_LATEX         = NO
QUIET                  = YES
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
WARN_AS_ERROR          = NO
