# Generated by squared-pg {{generator_version}} from {{template_id}} {{template_version}}.
#
# This file is GENERATED (ownership class: generated). Edits here are lost on
# the next update. Put your own rules in the Makefile, which is yours.

SQ_PROJECT       := {{project_name}}
SQ_CART_ID       := kit.{{project_name}}
SQ_TEMPLATE      := {{template_id}}
SQ_TEMPLATE_VER  := {{template_version}}

DIST             ?= dist

# The cartridge tool. Looked up in three places, most specific first: an
# explicit override, the environment's own bin directory, then $PATH.
#
# Not vendored into the workspace and not downloaded. A kit-authoring
# workspace legitimately depends on the toolchain that reads cartridges;
# pretending otherwise would mean shipping a copy of sqcart in every kit.
SQSYSROOT        ?= $(HOME)/sqsysroot
SQCART           ?= $(firstword $(wildcard $(SQSYSROOT)/.sqpg/bin/sqcart) \
                                $(shell command -v sqcart 2>/dev/null))
SQ_RESOURCES     ?= $(firstword $(wildcard $(SQSYSROOT)/.sqpg/resources))

# Read straight out of the manifest, so the version lives in exactly one
# place. sed rather than a JSON parser: the workspace must build with make and
# a shell, and adding a JSON dependency to read one field would be a poor
# trade (Generator Architecture 2.12).
SQ_CART_VERSION  := $(shell sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
                              cartridge/SQ-INF/manifest.json | head -1)

# Compression level for `make dist`. 0 stores, 9 is smallest, 6 is the
# default. The content digest is computed over uncompressed bytes, so the
# level changes the file size and nothing else.
SQ_COMPRESS      ?=
SQ_PACK_FLAGS    := $(if $(SQ_COMPRESS),--compress=$(SQ_COMPRESS),)

# Payload sources, for format and lint. Only under cartridge/tree/ -- the
# manifest is not a C++ file and the scaffolding is not yours to reformat.
SQ_PAYLOAD_SRC   := $(shell find cartridge/tree -name '*.cpp' -o -name '*.hpp' \
                              -o -name '*.c' -o -name '*.h' 2>/dev/null | sort)
