--- Demonstrates documentation generated by the private LDoc toolchain.
--
-- The text includes **Markdown** to exercise LDoc's bundled Markdown renderer.
-- @module toolchain_sample

local toolchain_sample = {}

--- Join a project name and action for diagnostic output.
-- @tparam string project Project name.
-- @tparam string action Action being performed.
-- @treturn string Human-readable diagnostic.
-- @raise If either argument is not a string.
function toolchain_sample.describe(project, action)
    assert(type(project) == "string", "project must be a string")
    assert(type(action) == "string", "action must be a string")

    return project .. ": " .. action
end

return toolchain_sample
