--- Explicit optional-module composition for generated projects.
-- @module sdl_pg.project_module

local lfs = require("lfs")
local fs = require("sdl_pg.fs")
local package_registry = require("sdl_pg.package_registry")
local path = require("sdl_pg.path")
local project = require("sdl_pg.project")

local project_module = {}
local state_relative = ".squared-pg/modules.lua"
local cmake_relative = ".squared-pg/modules.cmake"
local temporary_counter = 0

local function quote(value)
    return string.format("%q", value)
end

local function load_state(root)
    local filename = path.join(root, state_relative)
    if fs.mode(filename) ~= "file" then
        return {format = 1, modules = {}}
    end
    local chunk, message = loadfile(filename, "t", {})
    if not chunk then
        error("cannot load project module state: " .. tostring(message), 0)
    end
    local ok, state = pcall(chunk)
    if not ok or type(state) ~= "table" or state.format ~= 1 or
        type(state.modules) ~= "table" then
        error("invalid project module state", 0)
    end
    local identifiers = {}
    for _, record in ipairs(state.modules) do
        if type(record) ~= "table" or type(record.id) ~= "string" or
            type(record.version) ~= "string" or
            type(record.target) ~= "string" or
            type(record.directory) ~= "string" or
            type(record.content_digest) ~= "string" then
            error("invalid project module state record", 0)
        end
        if identifiers[record.id] then
            error("duplicate project module state: " .. record.id, 0)
        end
        identifiers[record.id] = true
    end
    return state
end

local function sorted_modules(modules)
    local result = {}
    for index, record in ipairs(modules) do result[index] = record end
    table.sort(result, function(left, right)
        if left.id ~= right.id then return left.id < right.id end
        return left.version < right.version
    end)
    return result
end

local function state_contents(modules)
    local lines = {
        "--- Managed by squared-pg project module commands.",
        "return {",
        "    format = 1,",
        "    modules = {"
    }
    for _, record in ipairs(sorted_modules(modules)) do
        lines[#lines + 1] = "        {"
        for _, field in ipairs({"id", "version", "target", "directory", "content_digest"}) do
            lines[#lines + 1] =
                "            " .. field .. " = " .. quote(record[field]) .. ","
        end
        lines[#lines + 1] = "        },"
    end
    lines[#lines + 1] = "    }"
    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""
    return table.concat(lines, "\n")
end

local function cmake_contents(profile, identifier, modules)
    local ordered = sorted_modules(modules)
    local lines = {
        "# Generated by squared-pg. Do not edit by hand."
    }
    if profile == "foundation" then
        lines[#lines + 1] = "enable_language(C)"
        lines[#lines + 1] = "set_property(GLOBAL PROPERTY SQUARED_MODULE_TARGETS \"\")"
        lines[#lines + 1] = "function(squared_register_module target)"
        lines[#lines + 1] = "    if(NOT TARGET \"${target}\")"
        lines[#lines + 1] = "        message(FATAL_ERROR \"Squared module target is missing: ${target}\")"
        lines[#lines + 1] = "    endif()"
        lines[#lines + 1] = "    set_property(GLOBAL APPEND PROPERTY SQUARED_MODULE_TARGETS \"${target}\")"
        lines[#lines + 1] = "endfunction()"
        for _, record in ipairs(ordered) do
            lines[#lines + 1] = string.format(
                "add_subdirectory(\"${CMAKE_CURRENT_LIST_DIR}/../%s\" " ..
                "\"${CMAKE_CURRENT_BINARY_DIR}/squared-modules/%s\")",
                record.directory,
                path.basename(record.directory)
            )
        end
        lines[#lines + 1] = "target_link_libraries(" .. identifier .. " PUBLIC"
    elseif profile == "android-sdl2-lua" then
        lines[#lines + 1] = "target_link_libraries(project_application PUBLIC"
    else
        error("project profile does not support optional modules: " .. tostring(profile), 0)
    end
    for _, record in ipairs(ordered) do
        lines[#lines + 1] = "    " .. record.target
    end
    lines[#lines + 1] = ")"
    lines[#lines + 1] = ""
    return table.concat(lines, "\n")
end

local function integration(profile, root)
    if profile == "android-sdl2-lua" then
        return path.join(root, "app/src/main/cpp/application/CMakeLists.txt"),
            table.concat({
                "# squared-pg optional modules",
                "include(\"${PROJECT_ROOT}/.squared-pg/modules.cmake\")"
            }, "\n")
    elseif profile == "foundation" then
        return path.join(root, "CMakeLists.txt"), table.concat({
            "# squared-pg optional modules",
            "include(\"${CMAKE_CURRENT_SOURCE_DIR}/.squared-pg/modules.cmake\")"
        }, "\n")
    end
    error("project profile does not support optional modules: " .. tostring(profile), 0)
end

local function atomic_write(filename, contents)
    temporary_counter = temporary_counter + 1
    local temporary = filename .. ".tmp-" .. tostring(os.time()) ..
        "-" .. tostring(temporary_counter)
    fs.write_file(temporary, contents)
    local backup = filename .. ".backup-" .. tostring(os.time()) ..
        "-" .. tostring(temporary_counter)
    local had_original = fs.mode(filename) == "file"
    if had_original then
        local moved, message = os.rename(filename, backup)
        if not moved then
            os.remove(temporary)
            error("cannot stage managed project file: " .. tostring(message), 0)
        end
    end
    local installed, message = os.rename(temporary, filename)
    if not installed then
        if had_original then os.rename(backup, filename) end
        os.remove(temporary)
        error("cannot install managed project file: " .. tostring(message), 0)
    end
    if had_original then os.remove(backup) end
end

local function walk(root, relative, files, directories)
    local current = relative == "" and root or path.join(root, relative)
    for _, entry in ipairs(fs.entries(current)) do
        local child_relative = relative == "" and entry or path.join(relative, entry)
        local child = path.join(root, child_relative)
        if fs.mode(child) == "directory" then
            directories[#directories + 1] = child_relative
            walk(root, child_relative, files, directories)
        else
            files[#files + 1] = child_relative
        end
    end
end

local function preflight_merge(stage, destination, files)
    for _, relative in ipairs(files) do
        if fs.exists(path.join(destination, relative)) then
            error("module file already exists in project: " ..
                path.join(destination, relative), 0)
        end
    end
end

local function rollback_merge(destination, files, directories)
    for _, relative in ipairs(files) do
        os.remove(path.join(destination, relative))
    end
    table.sort(directories, function(left, right) return #left > #right end)
    for _, relative in ipairs(directories) do
        lfs.rmdir(path.join(destination, relative))
    end
end

local function template_modules(settings, metadata)
    local result = {}
    if type(metadata.template) ~= "string" then return result end
    local identifier, version = metadata.template:match("^([^@]+)@([^@]+)$")
    if not identifier then return result end
    local ok, _, dependencies = pcall(
        package_registry.require_template, settings, identifier, version
    )
    if not ok then return result end
    for _, record in ipairs(dependencies) do
        if record.kind == "module" and record.module then
            result[record.module.directory] = record
        end
    end
    return result
end

local function record_for(package)
    return {
        id = package.id,
        version = package.version,
        target = package.module.cmake_target,
        directory = package.module.directory,
        content_digest = package.content_digest
    }
end

--- Add one exact registered module and missing transitive modules to a project.
-- @param settings Generator settings.
-- @param start Project directory or child.
-- @param identifier Exact module package identifier.
-- @param version Exact module version.
-- @return Composition summary.
function project_module.add(settings, start, identifier, version)
    local verification = project.verify(start or ".")
    if not verification.valid then error("project verification failed", 0) end
    local metadata = verification.project_metadata
    local profile = metadata and (metadata.profile or metadata.stage)
    local project_identifier = metadata and metadata.identifier
    if type(project_identifier) ~= "string" or project_identifier == "" then
        error("project.lua has no identifier", 0)
    end
    local integration_file, anchor = integration(profile, verification.root)
    if fs.mode(integration_file) ~= "file" then
        error("project CMake integration file is missing: " .. integration_file, 0)
    end

    local root, dependencies = package_registry.resolve(settings, identifier, version)
    if root.kind ~= "module" or not root.module then
        error("registered SQ package is not a module: " .. identifier, 0)
    end
    local ordered = {}
    for _, record in ipairs(dependencies) do ordered[#ordered + 1] = record end
    ordered[#ordered + 1] = root
    for _, record in ipairs(ordered) do
        if record.kind ~= "module" or not record.module then
            error("module dependency graph contains a non-module package: " .. record.id, 0)
        end
    end

    local state = load_state(verification.root)
    local managed_by_id = {}
    for _, record in ipairs(state.modules) do managed_by_id[record.id] = record end
    local existing_root = managed_by_id[root.id]
    if existing_root then
        if existing_root.version ~= root.version or
            existing_root.content_digest ~= root.content_digest then
            error("project module version conflicts with enabled content: " .. root.id, 0)
        end
        if fs.mode(path.join(verification.root, existing_root.directory)) ~=
                "directory" or
            fs.mode(path.join(verification.root, state_relative)) ~= "file" or
            fs.mode(path.join(verification.root, cmake_relative)) ~= "file" or
            not fs.read_file(integration_file):find(anchor, 1, true) then
            error("enabled project module integration is incomplete: " .. root.id, 0)
        end
        return {
            root = verification.root,
            coordinate = root.id .. "@" .. root.version,
            added = {},
            modules = sorted_modules(state.modules),
            already_enabled = true
        }
    end

    local provided = template_modules(settings, verification.metadata)
    local additions = {}
    for _, record in ipairs(ordered) do
        local managed = managed_by_id[record.id]
        if managed then
            if managed.version ~= record.version or
                managed.content_digest ~= record.content_digest then
                error("project module dependency conflict: " .. record.id, 0)
            end
        else
            local destination = path.join(verification.root, record.module.directory)
            if fs.exists(destination) then
                local built_in = provided[record.module.directory]
                if not built_in or built_in.id ~= record.id or
                    built_in.version ~= record.version then
                    error("unmanaged project module conflicts with " ..
                        record.id .. "@" .. record.version, 0)
                end
            else
                additions[#additions + 1] = record
            end
        end
    end

    local stage = path.join(
        verification.root,
        ".squared-pg-module-stage-" .. tostring(os.time()) ..
            "-" .. tostring(temporary_counter + 1)
    )
    if fs.exists(stage) then error("project module staging path already exists", 0) end
    fs.mkdir_p(stage)
    local ok, result = xpcall(function()
        for _, record in ipairs(additions) do
            package_registry.apply_module(
                settings, stage, record.id, record.version
            )
        end
        local files, directories = {}, {}
        walk(stage, "", files, directories)
        preflight_merge(stage, verification.root, files)

        local old_integration = fs.read_file(integration_file)
        local state_file = path.join(verification.root, state_relative)
        local cmake_file = path.join(verification.root, cmake_relative)
        local old_state = fs.mode(state_file) == "file" and fs.read_file(state_file) or nil
        local old_cmake = fs.mode(cmake_file) == "file" and fs.read_file(cmake_file) or nil
        local next_modules = {}
        for _, record in ipairs(state.modules) do next_modules[#next_modules + 1] = record end
        for _, record in ipairs(additions) do
            local value = record_for(record)
            next_modules[#next_modules + 1] = value
            managed_by_id[value.id] = value
        end

        local merged = false
        local changed_integration = false
        local committed, failure = xpcall(function()
            merged = true
            fs.merge_tree(stage, verification.root)
            if not old_integration:find(anchor, 1, true) then
                atomic_write(integration_file, old_integration:gsub("\n*$", "") ..
                    "\n\n" .. anchor .. "\n")
                changed_integration = true
            end
            atomic_write(state_file, state_contents(next_modules))
            atomic_write(cmake_file, cmake_contents(
                profile, project_identifier, next_modules
            ))
        end, debug.traceback)
        if not committed then
            if changed_integration then atomic_write(integration_file, old_integration) end
            if old_state then
                atomic_write(state_file, old_state)
            else
                os.remove(state_file)
            end
            if old_cmake then
                atomic_write(cmake_file, old_cmake)
            else
                os.remove(cmake_file)
            end
            if merged then rollback_merge(verification.root, files, directories) end
            error(failure, 0)
        end
        return {
            root = verification.root,
            coordinate = root.id .. "@" .. root.version,
            added = additions,
            modules = sorted_modules(next_modules),
            already_enabled = false
        }
    end, debug.traceback)
    if fs.exists(stage) then fs.remove_tree(stage) end
    if not ok then error(result, 0) end
    return result
end

--- List modules explicitly enabled through the project module workflow.
-- @param start Project directory or child.
-- @return Project root and ordered module records.
function project_module.status(start)
    local verification = project.verify(start or ".")
    if not verification.valid then error("project verification failed", 0) end
    return verification.root, sorted_modules(load_state(verification.root).modules)
end

return project_module
