--- Project creation and workspace transfer operations.
-- @module sdl_pg.project

local fs = require("sdl_pg.fs")
local path = require("sdl_pg.path")
local android = require("sdl_pg.android")

local project = {}
local marker_name = ".sdl-pg.lua"

local function quote_lua(value)
    return string.format("%q", value)
end

local function project_files(name)
    local identifier = path.identifier(name)
    local title = name:gsub("[-_]+", " ")
    title = title:gsub("^%l", string.upper)

    return {
        [marker_name] = table.concat({
            "return {",
            "    format = 1,",
            "    name = " .. quote_lua(name) .. ",",
            "    generator = \"sdl-pg\",",
            "    generator_version = \"0.4.0\"",
            "}",
            ""
        }, "\n"),
        ["project.lua"] = table.concat({
            "--- Project metadata consumed by sdl-pg.",
            "-- @script project",
            "",
            "return {",
            "    name = " .. quote_lua(name) .. ",",
            "    identifier = " .. quote_lua(identifier) .. ",",
            "    stage = \"foundation\"",
            "}",
            ""
        }, "\n"),
        ["README.md"] = table.concat({
            "---",
            "title: " .. title,
            "tags:",
            "  - cpp",
            "  - lua",
            "  - sdl",
            "status: experimental",
            "---",
            "",
            "# " .. title,
            "",
            "Generated by the `sdl-pg` foundation profile.",
            "",
            "Start with [[docs/Home|Project Home]].",
            "",
            "This foundation scaffold intentionally has no Android or SDL2",
            "integration yet.",
            ""
        }, "\n"),
        ["docs/Home.md"] = table.concat({
            "---",
            "title: " .. title .. " Home",
            "tags:",
            "  - project",
            "---",
            "",
            "# " .. title,
            "",
            "- [[../README|README]]",
            "- Public C++ API: `include/" ..
                identifier ..
                "/application.hpp`",
            "- Lua metadata: `project.lua`",
            ""
        }, "\n"),
        ["include/" .. identifier .. "/application.hpp"] = table.concat({
            "#pragma once",
            "",
            "namespace " .. identifier .. " {",
            "",
            "/**",
            " * @brief Return the generated project name.",
            " *",
            " * @return Stable UTF-8 project name.",
            " */",
            "[[nodiscard]] const char* project_name() noexcept;",
            "",
            "}  // namespace " .. identifier,
            ""
        }, "\n"),
        ["src/application.cpp"] = table.concat({
            "#include <" .. identifier .. "/application.hpp>",
            "",
            "namespace " .. identifier .. " {",
            "",
            "const char* project_name() noexcept",
            "{",
            "    return " .. string.format("%q", name) .. ";",
            "}",
            "",
            "}  // namespace " .. identifier,
            ""
        }, "\n"),
        ["src/main.cpp"] = table.concat({
            "#include <" .. identifier .. "/application.hpp>",
            "",
            "#include <cstdio>",
            "",
            "int main()",
            "{",
            "    std::printf(\"%s\\n\", " ..
                identifier ..
                "::project_name());",
            "    return 0;",
            "}",
            ""
        }, "\n"),
        ["CMakeLists.txt"] = table.concat({
            "cmake_minimum_required(VERSION 3.20)",
            "",
            "project(" ..
                identifier ..
                " VERSION 0.1.0 LANGUAGES CXX)",
            "",
            "add_library(" .. identifier,
            "    src/application.cpp",
            ")",
            "",
            "target_compile_features(" ..
                identifier ..
                " PUBLIC cxx_std_20)",
            "",
            "target_include_directories(" .. identifier,
            "    PUBLIC",
            "        include",
            ")",
            "",
            "target_compile_options(" .. identifier,
            "    PRIVATE",
            "        -Wall",
            "        -Wextra",
            "        -Wpedantic",
            ")",
            "",
            "add_executable(" .. identifier .. "_demo",
            "    src/main.cpp",
            ")",
            "",
            "target_link_libraries(" .. identifier .. "_demo",
            "    PRIVATE",
            "        " .. identifier,
            ")",
            ""
        }, "\n")
    }
end

local function require_marker(source, reject_git)
    if fs.mode(path.join(source, marker_name)) ~= "file" then
        error("source is not an sdl-pg project: " .. source, 0)
    end

    if reject_git and fs.exists(path.join(source, ".git")) then
        error(
            "source contains .git; repository transfer requires " ..
            "an explicit manual decision",
            0
        )
    end
end

--- Create a new generated project.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @param location Either `sandbox` or `project`.
-- @param[opt] options Profile-specific generation options.
-- @return Created directory.
function project.create(settings, name, location, options)
    path.validate_project_name(name)
    options = options or {profile = "foundation"}

    local root
    if location == "sandbox" then
        root = settings.sandbox_root
    elseif location == "project" then
        root = settings.projects_root
    else
        error("location must be 'sandbox' or 'project'", 0)
    end

    fs.mkdir_p(root)
    local destination = path.join(root, name)

    if fs.exists(destination) then
        error("destination already exists: " .. destination, 0)
    end

    local temporary =
        destination .. ".sdl-pg-new-" .. tostring(os.time())
    local counter = 0

    while fs.exists(temporary) do
        counter = counter + 1
        temporary =
            destination ..
            ".sdl-pg-new-" ..
            tostring(os.time()) ..
            "-" ..
            tostring(counter)
    end

    local ok, message = xpcall(function()
        fs.mkdir_p(temporary)

        if options.profile == "android" then
            android.populate(settings, temporary, name, options)
        elseif options.profile == "foundation" then
            for filename, contents in pairs(project_files(name)) do
                fs.write_file(path.join(temporary, filename), contents)
            end
        else
            error("unknown project profile: " ..
                tostring(options.profile), 0)
        end
    end, debug.traceback)

    if not ok then
        if fs.exists(temporary) then
            fs.remove_tree(temporary)
        end
        error(message, 0)
    end

    local renamed, rename_message = os.rename(temporary, destination)
    if not renamed then
        fs.remove_tree(temporary)
        error(
            "cannot finalize project " ..
            destination ..
            ": " ..
            tostring(rename_message),
            0
        )
    end

    return destination
end

local function transfer(
    settings,
    name,
    source_root,
    destination_root,
    demoting
)
    path.validate_project_name(name)
    local source = path.join(source_root, name)
    local destination = path.join(destination_root, name)

    require_marker(source, not demoting)
    local excluded_names = demoting and {[".git"] = true} or nil
    fs.copy_tree_transactional(source, destination, excluded_names)
    return destination
end

--- Copy a generated project from sandbox to projects.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @return Destination directory.
function project.promote(settings, name)
    return transfer(
        settings,
        name,
        settings.sandbox_root,
        settings.projects_root,
        false
    )
end

--- Copy a generated project from projects to sandbox.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @return Destination directory.
function project.demote(settings, name)
    return transfer(
        settings,
        name,
        settings.projects_root,
        settings.sandbox_root,
        true
    )
end

return project
