--- Project creation and workspace transfer operations.
-- @module sdl_pg.project

local fs = require("sdl_pg.fs")
local path = require("sdl_pg.path")
local process = require("sdl_pg.process")
local provider = require("sdl_pg.provider")
local release = require("sdl_pg.version")

local project = {}
local marker_name = ".squared-pg.lua"
local legacy_marker_name = ".sdl-pg.lua"

local function quote_lua(value)
    return string.format("%q", value)
end

local function project_files(name)
    local identifier = path.identifier(name)
    local title = name:gsub("[-_]+", " ")
    title = title:gsub("^%l", string.upper)

    return {
        [marker_name] = table.concat({
            "return {",
            "    format = 1,",
            "    name = " .. quote_lua(name) .. ",",
            "    generator = \"squared-pg\",",
            "    generator_version = " .. quote_lua(release.version),
            "}",
            ""
        }, "\n"),
        ["project.lua"] = table.concat({
            "--- Project metadata consumed by squared-pg.",
            "-- @script project",
            "",
            "return {",
            "    name = " .. quote_lua(name) .. ",",
            "    identifier = " .. quote_lua(identifier) .. ",",
            "    stage = \"foundation\"",
            "}",
            ""
        }, "\n"),
        ["README.md"] = table.concat({
            "---",
            "title: " .. title,
            "tags:",
            "  - cpp",
            "  - lua",
            "  - sdl",
            "status: experimental",
            "---",
            "",
            "# " .. title,
            "",
            "Generated by the `squared-pg` foundation profile.",
            "",
            "Start with [[docs/Home|Project Home]].",
            "",
            "This foundation scaffold intentionally has no Android or SDL2",
            "integration yet.",
            ""
        }, "\n"),
        ["docs/Home.md"] = table.concat({
            "---",
            "title: " .. title .. " Home",
            "tags:",
            "  - project",
            "---",
            "",
            "# " .. title,
            "",
            "- [[../README|README]]",
            "- Public C++ API: `include/" ..
                identifier ..
                "/application.hpp`",
            "- Lua metadata: `project.lua`",
            ""
        }, "\n"),
        ["include/" .. identifier .. "/application.hpp"] = table.concat({
            "#pragma once",
            "",
            "namespace " .. identifier .. " {",
            "",
            "/**",
            " * @brief Return the generated project name.",
            " *",
            " * @return Stable UTF-8 project name.",
            " */",
            "[[nodiscard]] const char* project_name() noexcept;",
            "",
            "}  // namespace " .. identifier,
            ""
        }, "\n"),
        ["src/application.cpp"] = table.concat({
            "#include <" .. identifier .. "/application.hpp>",
            "",
            "namespace " .. identifier .. " {",
            "",
            "const char* project_name() noexcept",
            "{",
            "    return " .. string.format("%q", name) .. ";",
            "}",
            "",
            "}  // namespace " .. identifier,
            ""
        }, "\n"),
        ["src/main.cpp"] = table.concat({
            "#include <" .. identifier .. "/application.hpp>",
            "",
            "#include <cstdio>",
            "",
            "int main()",
            "{",
            "    std::printf(\"%s\\n\", " ..
                identifier ..
                "::project_name());",
            "    return 0;",
            "}",
            ""
        }, "\n"),
        ["CMakeLists.txt"] = table.concat({
            "cmake_minimum_required(VERSION 3.20)",
            "",
            "project(" ..
                identifier ..
                " VERSION 0.1.0 LANGUAGES CXX)",
            "",
            "add_library(" .. identifier,
            "    src/application.cpp",
            ")",
            "",
            "target_compile_features(" ..
                identifier ..
                " PUBLIC cxx_std_20)",
            "",
            "target_include_directories(" .. identifier,
            "    PUBLIC",
            "        include",
            ")",
            "",
            "target_compile_options(" .. identifier,
            "    PRIVATE",
            "        -Wall",
            "        -Wextra",
            "        -Wpedantic",
            ")",
            "",
            "add_executable(" .. identifier .. "_demo",
            "    src/main.cpp",
            ")",
            "",
            "target_link_libraries(" .. identifier .. "_demo",
            "    PRIVATE",
            "        " .. identifier,
            ")",
            ""
        }, "\n")
    }
end

local function load_table(filename, label)
    local chunk, message = loadfile(filename, "t", {})
    if not chunk then
        error("cannot load " .. label .. ": " .. tostring(message), 0)
    end
    local ok, result = pcall(chunk)
    if not ok or type(result) ~= "table" then
        error("invalid " .. label .. ": " .. tostring(result), 0)
    end
    return result
end

--- Find the nearest generated-project root at or above a directory.
-- @param start Starting directory.
-- @return Project root and marker filename, or nil.
function project.find_root(start)
    local current = tostring(start or "."):gsub("/+$", "")
    if current == "" then current = "/" end
    while true do
        if fs.mode(path.join(current, marker_name)) == "file" then
            return current, marker_name
        end
        if fs.mode(path.join(current, legacy_marker_name)) == "file" then
            return current, legacy_marker_name
        end
        if current == "/" or current == "." then
            return nil
        end
        local parent = path.dirname(current)
        if parent == current then
            return nil
        end
        current = parent
    end
end

--- Verify the identity and metadata of a generated project.
-- @param start Project directory or a child directory.
-- @return Verification report.
function project.verify(start)
    local root, marker = project.find_root(start or ".")
    if not root then
        error("no squared-pg project found at or above: " .. tostring(start), 0)
    end
    local metadata = load_table(path.join(root, marker), "project marker")
    local issues = {}
    local function issue(message)
        issues[#issues + 1] = message
    end
    if marker ~= marker_name then
        issue("legacy marker in use: " .. legacy_marker_name)
    end
    if metadata.generator ~= "squared-pg" then
        issue("project marker generator is not squared-pg")
    end
    if type(metadata.name) ~= "string" or metadata.name == "" then
        issue("project marker has no name")
    end
    if type(metadata.generator_version) ~= "string" then
        issue("project marker has no generator_version")
    end
    if fs.exists(path.join(root, legacy_marker_name)) and
        fs.exists(path.join(root, marker_name)) then
        issue("both primary and legacy project markers exist")
    end
    local project_metadata
    local project_filename = path.join(root, "project.lua")
    if fs.mode(project_filename) ~= "file" then
        issue("project.lua is missing")
    else
        project_metadata = load_table(project_filename, "project.lua")
        if project_metadata.name ~= metadata.name then
            issue("project.lua name does not match the project marker")
        end
        if project_metadata.generator_version and
            project_metadata.generator_version ~= metadata.generator_version then
            issue("project.lua generator_version does not match the marker")
        end
        if project_metadata.template and metadata.template and
            project_metadata.template ~= metadata.template then
            issue("project.lua template does not match the marker")
        end
    end
    for _, relative in ipairs({
        "app/src/main/assets/lua/sdl_pg/provider.lua",
        "app/src/main/assets/lua/sdl_pg/dependency.lua"
    }) do
        if fs.exists(path.join(root, relative)) then
            issue("generator-only module leaked into project: " .. relative)
        end
    end
    return {
        root = root,
        marker = marker,
        metadata = metadata,
        project_metadata = project_metadata,
        valid = #issues == 0,
        issues = issues
    }
end

--- Build a generated project through its checked-in build entry point.
-- @param start Project directory or a child directory.
-- @param[opt] options Build options: clean, online_once, and lua.
-- @return Build summary.
function project.build(start, options)
    options = options or {}
    local verification = project.verify(start or ".")
    if not verification.valid then error("project verification failed", 0) end
    local builder = path.join(verification.root, "tools/build.lua")
    if fs.mode(builder) ~= "file" then
        error("generated project build entry point is missing: " .. builder, 0)
    end
    local arguments = {options.lua or "lua5.4", builder}
    if options.clean then arguments[#arguments + 1] = "--clean" end
    if options.online_once then arguments[#arguments + 1] = "--online-once" end
    process.run(arguments, verification.root)
    return {
        root = verification.root,
        builder = builder,
        clean = options.clean == true,
        online_once = options.online_once == true
    }
end

local function require_marker(source, reject_git)
    if fs.mode(path.join(source, marker_name)) ~= "file" and
        fs.mode(path.join(source, legacy_marker_name)) ~= "file" then
        error("source is not a squared-pg project: " .. source, 0)
    end

    if reject_git and fs.exists(path.join(source, ".git")) then
        error(
            "source contains .git; repository transfer requires " ..
            "an explicit manual decision",
            0
        )
    end
end

--- Create a new generated project.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @param location Either `sandbox` or `project`.
-- @param[opt] options Profile-specific generation options.
-- @return Created directory.
function project.create(settings, name, location, options)
    path.validate_project_name(name)
    options = options or {profile = "foundation"}

    local root
    if location == "sandbox" then
        root = settings.sandbox_root
    elseif location == "project" then
        root = settings.projects_root
    else
        error("location must be 'sandbox' or 'project'", 0)
    end

    fs.mkdir_p(root)
    local destination = path.join(root, name)

    if fs.exists(destination) then
        error("destination already exists: " .. destination, 0)
    end

    local provider_resolution
    if options.profile == "template" then
        provider_resolution = provider.resolve(settings, name, options)
    elseif options.profile ~= "foundation" then
        error("unknown project profile: " .. tostring(options.profile), 0)
    end

    local temporary =
        destination .. ".squared-pg-new-" .. tostring(os.time())
    local counter = 0

    while fs.exists(temporary) do
        counter = counter + 1
        temporary =
            destination ..
            ".squared-pg-new-" ..
            tostring(os.time()) ..
            "-" ..
            tostring(counter)
    end

    local ok, message = xpcall(function()
        fs.mkdir_p(temporary)

        if options.profile == "template" then
            provider.populate(
                settings,
                temporary,
                name,
                options,
                provider_resolution
            )
        elseif options.profile == "foundation" then
            for filename, contents in pairs(project_files(name)) do
                fs.write_file(path.join(temporary, filename), contents)
            end
        end
    end, debug.traceback)

    if not ok then
        if fs.exists(temporary) then
            fs.remove_tree(temporary)
        end
        error(message, 0)
    end

    local renamed, rename_message = os.rename(temporary, destination)
    if not renamed then
        fs.remove_tree(temporary)
        error(
            "cannot finalize project " ..
            destination ..
            ": " ..
            tostring(rename_message),
            0
        )
    end

    return destination
end

local function transfer(
    settings,
    name,
    source_root,
    destination_root,
    demoting
)
    path.validate_project_name(name)
    local source = path.join(source_root, name)
    local destination = path.join(destination_root, name)

    require_marker(source, not demoting)
    local excluded_names = demoting and {[".git"] = true} or nil
    fs.copy_tree_transactional(source, destination, excluded_names)
    return destination
end

--- Copy a generated project from sandbox to projects.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @return Destination directory.
function project.promote(settings, name)
    return transfer(
        settings,
        name,
        settings.sandbox_root,
        settings.projects_root,
        false
    )
end

--- Copy a generated project from projects to sandbox.
-- @param settings Resolved configuration.
-- @param name Project name.
-- @return Destination directory.
function project.demote(settings, name)
    return transfer(
        settings,
        name,
        settings.projects_root,
        settings.sandbox_root,
        true
    )
end

return project
